/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ISherlock } from "./ISherlock";

export { ISherlock__factory } from "./factories/ISherlock__factory";
